# Generated by Django 3.0.6 on 2020-05-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_auto_20200512_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='NewsApp.Category', verbose_name='Категория'),
        ),
    ]
